export type WorldCountries = 
    | 'India' 
    | 'Saudia Arabia' 
    | 'Philippines' 
    | 'China' 
    | 'Chile' 
    | 'Korea' 
    | 'Mexico' 
    | 'Montenegro' 
    | 'Turkey' 
    | 'Poland' 
    | 'France' 
    | 'Italy' 
    | 'Denmark' 
    | 'Germany' 
    | 'Great Britain' 
    | 'Spain' 
    | 'Norway' 
    | 'Australia' 
    | 'Iceland' 
    | 'Switzerland';

export type WorldCountriesCities = 
    | 'Delhi' 
    | 'Riyadh' 
    | 'Manila' 
    | 'Beijing' 
    | 'Santiago' 
    | 'Seoul' 
    | 'Mexico City' 
    | 'Podgorica' 
    | 'Istanbul' 
    | 'Warszawa' 
    | 'Paris' 
    | 'Roma' 
    | 'Copenhagen' 
    | 'Berlin' 
    | 'London' 
    | 'Madrid' 
    | 'Oslo' 
    | 'Sydney' 
    | 'Reykjavik' 
    | 'Zurich';